services:
  - type: web
    name: investment-platform-backend
    env: node
    plan: free
        buildCommand: npm install && npm run build && npm run migrate
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: investment-platform-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: investment-platform-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://quantumpips.co,https://www.quantumpips.co
    autoDeploy: true
    branch: main
    rootDir: .
    dockerfilePath: ./Dockerfile
    dockerContext: .
    
  - type: pserv
    name: investment-platform-db
    plan: free
    env: postgres
    envVars:
      - key: POSTGRES_DB
        value: investment_platform
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        generateValue: true
    disk:
      name: postgres-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1

  - type: redis
    name: investment-platform-redis
    plan: free
    envVars:
      - key: REDIS_PASSWORD
        generateValue: true
